spring:
  datasource:
    url: jdbc:mysql://localhost:3306/modle?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:file:.env[.properties]
    cloud:
      gcp:
        storage:
          # .env 파일의 GCP_PROJECT_ID 값을 주입
          project-id: ${GCP_PROJECT_ID}
          credentials:
            # .env 파일의 GCS_CREDENTIALS_PATH 값을 주입
            location: ${GCS_CREDENTIALS_PATH}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1800000
  refresh-expiration: 604800000

# 커스텀 설정: 버킷 이름을 전역으로 사용하기 위해 정의
gcs:
  bucket: ${GCS_BUCKET_NAME}
