/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 계약서 임시 저장
         * @description 계약 조건을 입력받아 DRAFT 상태의 계약서를 생성합니다.
         */
        post: operations["createContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 계약서 생성 요청 */
        ContractCreateRequest: {
            /** Format: int64 */
            applicationId: number;
            /** @enum {string} */
            contractType: "TEMPLATE" | "FILE";
            /** Format: date-time */
            shootStartAt: string;
            /** Format: date-time */
            shootEndAt: string;
            location: string;
            payment: number;
            /** @enum {string} */
            payType: "CASH" | "SERVICE";
            usageScope: string;
            memo?: string;
            pdfUrl?: string;
        };
        ContractResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            applicationId?: number;
            /** @enum {string} */
            contractType?: "TEMPLATE" | "FILE";
            /** Format: date-time */
            shootStartAt?: string;
            /** Format: date-time */
            shootEndAt?: string;
            location?: string;
            payment?: number;
            /** @enum {string} */
            payType?: "CASH" | "SERVICE";
            usageScope?: string;
            memo?: string;
            pdfUrl?: string;
            signedPdfUrl?: string;
            /** @enum {string} */
            status?: "DRAFT" | "NOTIFIED" | "VIEWED" | "AGREED" | "REJECTED" | "CONFIRMED" | "CANCELLED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContractResponse"];
                };
            };
        };
    };
}
